  language: python
  python:
    - "3.5.2"
  install:
    - pip install coverage
    - pip install coveralls
    - pip install -r requirements.txt

  script:
    - python3 -m pytest

  after_success:
    - coveralls

